// Shared by the visible page, static HTML metadata, and structured data.
export const SEO_CONTENT = {
  pt: {
    language: 'pt-BR', ogLocale: 'pt_BR',
    title: 'Calculadora AWS Fargate e Spot: estime custos | Fidalgo',
    heading: 'Calculadora de custos AWS Fargate',
    description: 'Calcule os custos de AWS Fargate e Fargate Spot por região, vCPU, memória e tarefas. Compare estimativas por hora ou mês e converta para reais ou outras moedas.',
    imageAlt: 'Calculadora AWS Fargate e Fargate Spot da Fidalgo IT Solutions',
    guideTitle: 'Como calcular o preço do AWS Fargate',
    guideIntro: 'Esta calculadora gratuita estima os custos de CPU e memória de contêineres Linux/x86. Compare Fargate e Fargate Spot em 22 regiões AWS, incluindo São Paulo (sa-east-1).',
    steps: [
      'Escolha a região AWS e a moeda da estimativa. Para um orçamento em reais, selecione BRL; o preço base em USD é convertido com o câmbio disponível.',
      'Defina a quantidade de vCPU e a memória em GiB de cada tarefa. A calculadora oferece as combinações de CPU e memória compatíveis com o Fargate.',
      'Informe o tempo de execução e a quantidade de tarefas Fargate e Fargate Spot que executarão simultaneamente. Confira o total e a composição por CPU e memória.',
    ],
    formulaTitle: 'Fórmula e exemplo de custo mensal',
    formula: 'Custo = tarefas × horas × [(vCPU × preço por vCPU/h) + (memória × preço por GB/h)]',
    assumptions: 'O cálculo pressupõe que todas as tarefas usam os mesmos recursos e permanecem em execução durante todo o período. Um dia equivale a 24 horas, um mês a 730 horas e um ano a 8.760 horas. Para uso parcial, informe as horas efetivas.',
    example: 'Exemplo: uma tarefa Linux/x86 em US East (N. Virginia), com 1 vCPU e 2 GiB de memória durante 730 horas, custa cerca de US$ 36,04 em Fargate. O exemplo usa US$ 0,04048 por vCPU/h e US$ 0,004445 por GB/h da tabela da calculadora.',
    sourcesTitle: 'Fontes dos preços e limites da estimativa',
    sources: 'As tarifas de CPU e memória foram verificadas em 29 de setembro de 2026. Os preços Spot são uma fotografia daquela consulta e podem variar. A conversão de moeda utiliza o câmbio do serviço ExchangeRate-API.',
    limits: 'A estimativa não inclui armazenamento adicional, transferência de dados, logs, impostos ou outros serviços AWS. ARM/Graviton e Windows não estão cobertos. A cobrança real da AWS considera a duração de execução e as regras mínimas de cobrança do serviço.',
    pricingLink: 'Consultar preços e regras de cobrança da AWS',
    dataLink: 'Consultar tarifas utilizadas pela calculadora',
    exchangeLink: 'Fonte das taxas de câmbio',
    faqTitle: 'Perguntas frequentes sobre custos do Fargate',
    faq: [
      { question: 'Como é calculado o custo do AWS Fargate?', answer: 'O custo de processamento depende da região, das vCPU e da memória configuradas, do número de tarefas e do tempo de execução. Esta calculadora multiplica as tarifas de CPU e memória pelos recursos, pelas horas e pela quantidade de tarefas. Outros serviços podem gerar cobranças adicionais.' },
      { question: 'Qual é a diferença entre Fargate e Fargate Spot?', answer: 'Fargate oferece capacidade sob demanda. Fargate Spot utiliza capacidade excedente com preços variáveis e pode interromper tarefas, com aviso de dois minutos. É indicado para cargas que toleram interrupções. Nesta calculadora, Spot se aplica a tarefas Linux/x86 no Amazon ECS.' },
      { question: 'Posso calcular o Fargate em reais e na região de São Paulo?', answer: 'Sim. Selecione South America (São Paulo), código sa-east-1, e BRL para converter a estimativa de USD para reais. A conversão é indicativa e não representa o valor final de uma fatura AWS, que pode incluir impostos e outros ajustes.' },
      { question: 'Quantas horas a calculadora considera em um mês?', answer: 'Um mês corresponde a 730 horas nesta calculadora. Um dia tem 24 horas e um ano tem 8.760 horas. Para tarefas que executam apenas parte do mês, selecione horas e informe o tempo de execução esperado.' },
      { question: 'Esta calculadora inclui todos os custos da AWS?', answer: 'Não. O total cobre apenas CPU e memória do Fargate e do Fargate Spot em Linux/x86. Armazenamento adicional, tráfego de dados, logs, impostos e outros serviços ficam fora da estimativa. Consulte os preços oficiais para avaliar o custo completo.' },
      { question: 'A calculadora é oficial da AWS?', answer: 'Não. É uma ferramenta gratuita e independente da Fidalgo IT Solutions, sem afiliação com a Amazon Web Services. Use as estimativas para planejamento e confirme os preços atuais com a AWS.' },
    ],
  },
  en: {
    language: 'en', ogLocale: 'en_US',
    title: 'AWS Fargate & Spot Pricing Calculator | Fidalgo',
    heading: 'AWS Fargate Pricing Calculator',
    description: 'Estimate AWS Fargate and Fargate Spot costs by region, vCPU, memory and task count. Compare hourly or monthly costs and convert estimates to your currency.',
    imageAlt: 'AWS Fargate and Fargate Spot pricing calculator by Fidalgo IT Solutions',
    guideTitle: 'How to calculate AWS Fargate pricing',
    guideIntro: 'This free calculator estimates CPU and memory costs for Linux/x86 containers. Compare Fargate and Fargate Spot across 22 AWS regions, including São Paulo (sa-east-1).',
    steps: [
      'Choose the AWS region and estimate currency. Base prices in USD are converted using the available exchange rate.',
      'Set the vCPU count and memory in GiB for each task. The calculator offers compatible Fargate CPU and memory combinations.',
      'Enter the runtime and number of Fargate and Fargate Spot tasks running concurrently. Review the total and the CPU and memory breakdown.',
    ],
    formulaTitle: 'Monthly cost formula and example',
    formula: 'Cost = tasks × hours × [(vCPU × price per vCPU/h) + (memory × price per GB/h)]',
    assumptions: 'The calculation assumes every task uses the same resources and runs for the entire period. A day equals 24 hours, a month 730 hours, and a year 8,760 hours. For part-time workloads, enter the actual runtime in hours.',
    example: 'Example: one Linux/x86 task in US East (N. Virginia) with 1 vCPU and 2 GiB of memory running for 730 hours costs approximately US$36.04 on Fargate. This uses US$0.04048 per vCPU/h and US$0.004445 per GB/h from the calculator’s price table.',
    sourcesTitle: 'Pricing sources and estimate limitations',
    sources: 'CPU and memory rates were checked on September 29, 2026. Spot rates are a snapshot from that check and can change. Currency conversion uses exchange rates from ExchangeRate-API.',
    limits: 'The estimate excludes additional storage, data transfer, logs, taxes, and other AWS services. ARM/Graviton and Windows are not covered. Actual AWS billing accounts for runtime and the service’s minimum billing rules.',
    pricingLink: 'Read official AWS pricing and billing rules',
    dataLink: 'View the rates used by this calculator',
    exchangeLink: 'Exchange rate source',
    faqTitle: 'Frequently asked questions about Fargate costs',
    faq: [
      { question: 'How is AWS Fargate cost calculated?', answer: 'Compute cost depends on the region, configured vCPU and memory, task count, and runtime. This calculator multiplies CPU and memory rates by resources, hours, and the number of tasks. Other services may add charges.' },
      { question: 'What is the difference between Fargate and Fargate Spot?', answer: 'Fargate provides on-demand capacity. Fargate Spot uses spare capacity with variable pricing and can interrupt tasks with a two-minute warning. It suits workloads that tolerate interruptions. In this calculator, Spot applies to Linux/x86 tasks on Amazon ECS.' },
      { question: 'Can I estimate Fargate costs in Brazilian reais for São Paulo?', answer: 'Yes. Select South America (São Paulo), region code sa-east-1, and BRL to convert the USD estimate to Brazilian reais. Conversion is indicative and does not represent a final AWS invoice, which may include taxes and other adjustments.' },
      { question: 'How many hours does the calculator use for a month?', answer: 'A month equals 730 hours in this calculator. A day has 24 hours and a year has 8,760 hours. For tasks running during only part of a month, choose hours and enter the expected runtime.' },
      { question: 'Does this calculator include all AWS costs?', answer: 'No. The total covers only Fargate and Fargate Spot CPU and memory for Linux/x86. Additional storage, data transfer, logs, taxes, and other services are excluded. Consult official pricing to assess the complete cost.' },
      { question: 'Is this an official AWS calculator?', answer: 'No. This is a free, independent tool by Fidalgo IT Solutions, with no affiliation with Amazon Web Services. Use estimates for planning and confirm current prices with AWS.' },
    ],
  },
  es: {
    language: 'es', ogLocale: 'es_ES',
    title: 'Calculadora de precios AWS Fargate y Spot | Fidalgo',
    heading: 'Calculadora de costos AWS Fargate',
    description: 'Calcula los costos de AWS Fargate y Fargate Spot por región, vCPU, memoria y tareas. Compara estimaciones por hora o mes y conviértelas a tu moneda.',
    imageAlt: 'Calculadora de precios AWS Fargate y Fargate Spot de Fidalgo IT Solutions',
    guideTitle: 'Cómo calcular el precio de AWS Fargate',
    guideIntro: 'Esta calculadora gratuita estima costos de CPU y memoria para contenedores Linux/x86. Compara Fargate y Fargate Spot en 22 regiones AWS, incluida São Paulo (sa-east-1).',
    steps: [
      'Elige la región AWS y la moneda de la estimación. Los precios base en USD se convierten con el tipo de cambio disponible.',
      'Define las vCPU y la memoria en GiB de cada tarea. La calculadora ofrece combinaciones de CPU y memoria compatibles con Fargate.',
      'Introduce la duración y la cantidad de tareas Fargate y Fargate Spot que se ejecutarán simultáneamente. Revisa el total y el desglose de CPU y memoria.',
    ],
    formulaTitle: 'Fórmula y ejemplo de costo mensual',
    formula: 'Costo = tareas × horas × [(vCPU × precio por vCPU/h) + (memoria × precio por GB/h)]',
    assumptions: 'El cálculo supone que todas las tareas usan los mismos recursos y se ejecutan durante todo el período. Un día equivale a 24 horas, un mes a 730 horas y un año a 8.760 horas. Para uso parcial, introduce las horas efectivas.',
    example: 'Ejemplo: una tarea Linux/x86 en US East (N. Virginia), con 1 vCPU y 2 GiB de memoria durante 730 horas, cuesta aproximadamente US$ 36,04 en Fargate. El ejemplo usa US$ 0,04048 por vCPU/h y US$ 0,004445 por GB/h de la tabla de la calculadora.',
    sourcesTitle: 'Fuentes de precios y límites de la estimación',
    sources: 'Las tarifas de CPU y memoria se verificaron el 29 de septiembre de 2026. Los precios Spot son una referencia de esa consulta y pueden cambiar. La conversión de moneda utiliza tipos de cambio de ExchangeRate-API.',
    limits: 'La estimación excluye almacenamiento adicional, transferencia de datos, logs, impuestos y otros servicios AWS. No cubre ARM/Graviton ni Windows. La facturación real de AWS considera la duración y las reglas mínimas de cobro del servicio.',
    pricingLink: 'Consultar precios y reglas de cobro oficiales de AWS',
    dataLink: 'Ver las tarifas utilizadas por la calculadora',
    exchangeLink: 'Fuente de tipos de cambio',
    faqTitle: 'Preguntas frecuentes sobre los costos de Fargate',
    faq: [
      { question: '¿Cómo se calcula el costo de AWS Fargate?', answer: 'El costo de procesamiento depende de la región, las vCPU y memoria configuradas, la cantidad de tareas y su duración. Esta calculadora multiplica las tarifas de CPU y memoria por los recursos, las horas y el número de tareas. Otros servicios pueden generar cargos adicionales.' },
      { question: '¿Cuál es la diferencia entre Fargate y Fargate Spot?', answer: 'Fargate ofrece capacidad bajo demanda. Fargate Spot utiliza capacidad sobrante con precios variables y puede interrumpir tareas con un aviso de dos minutos. Es adecuado para cargas que toleran interrupciones. En esta calculadora, Spot se aplica a tareas Linux/x86 en Amazon ECS.' },
      { question: '¿Puedo calcular Fargate en reales brasileños para São Paulo?', answer: 'Sí. Selecciona South America (São Paulo), código sa-east-1, y BRL para convertir la estimación de USD a reales brasileños. La conversión es indicativa y no representa la factura final de AWS, que puede incluir impuestos y otros ajustes.' },
      { question: '¿Cuántas horas considera la calculadora en un mes?', answer: 'Un mes equivale a 730 horas en esta calculadora. Un día tiene 24 horas y un año tiene 8.760 horas. Para tareas que se ejecutan solo parte del mes, selecciona horas e introduce la duración prevista.' },
      { question: '¿Esta calculadora incluye todos los costos de AWS?', answer: 'No. El total cubre solo CPU y memoria de Fargate y Fargate Spot en Linux/x86. El almacenamiento adicional, tráfico, logs, impuestos y otros servicios quedan fuera de la estimación. Consulta los precios oficiales para evaluar el costo completo.' },
      { question: '¿Es una calculadora oficial de AWS?', answer: 'No. Es una herramienta gratuita e independiente de Fidalgo IT Solutions, sin afiliación con Amazon Web Services. Usa las estimaciones para planificar y confirma los precios actuales con AWS.' },
    ],
  },
};
